### PR TITLE
Update Flink version to 1.16.1

### PR DESCRIPTION
**Pull request by erwan**

### CODE REVIEW

**Comment by novakov-alexey** [comment]
@shuttie would you be so kind to review and merge this PR?

**Comment by shuttie** [comment]
The problem is that I don't work on Findify anymore, so I'm not the maintainer and cannot merge PRs anymore. I've contacted Findify folks about the future of this project and will keep you posted on it.

I'm OK to spend some time supporting the project (and flink-scala-api also) on community grounds, but as the project was originally made under the Findify umbrella, there should be some steps taken from their side.

**Comment by novakov-alexey** [comment]
I see, thanks for clarification. Hopefully it will move forward.  

I think we need to probe an idea of making the findify/flink-scala-api as new official Scala API in the org.apache.flink, i.e. move the entire project to Apache umbrella.

**Comment by erwan** [comment]
I don't think it's necessary or even desirable to bring back any form of official Scala API to Flink.

It's perfectly fine if it's a third party wrapper, but if Findify doesn't want to maintain it, then it should be transferred to a new github org created for that purpose.

**Comment by novakov-alexey** [comment]
Let's wait for a Findify answer and a feedback from @shuttie.
@erwan will you be ready create new GitHub org for Scala wrapper and commit yourself for next 10 years to maintain such wrapper?

P.S. I am already tired to see abandoned Scala projects since I started to use Scala 8 years ago. It is a already a cemetery of different Scala libraries related to Big Data, Data Science, because they were so to speak 3-rd party. I do not want to do one more experiment with Flink Scala wrapper. The only viable way for future Scala application in Flink is to have Scala wrapper as part of org.apache.flink. Still main Flink modules will be Scala-free. Module Dependency should be only from Scala wrapper to Flink Java modules, opposite dependency is forbidden.

**Comment by novakov-alexey** [comment]
@shuttie did you get any response from Findify? I am wondering whether we should just fork this repo and continue ourselves.

**Comment by erwan** [comment]
@novakov-alexey no honestly I'm not willing to commit to maintain a wrapper. Mostly because I don't think I know enough about Flink to do it correctly. To give an example I found an issue recently #71 and I have no idea how to fix it.

That said I'd be happy to give a hand if someone else wants to take ownership.

I totally understand what you're saying about dying wrappers, which is why I'm not willing to take ownership of a module if I'm not sure I will be able and willing to keep it alive long term.

**Comment by shuttie** [comment]
As a main author of this thing, I have no problem continuing to maintain the project on community grounds. The problem is about project rights - noone can at this moment merge PRs, and I'm trying to contact anyone from Findify regarding this.

**Comment by erwan** [comment]
@shuttie any news on moving to a community Github organization?

**Comment by mzuehlke** [comment]
> @shuttie any news on moving to a community Github organization?

I spotted a start https://github.com/flink-extended/flink-scala-api

**Comment by novakov-alexey** [comment]
@mzuehlke indeed, we will soon announce a new iteration of the flink-scala-api being a part of the Flink Extended organisation. I am waiting for @shuttie to review last PR there.

**Comment by mzuehlke** [comment]
Thanks for the activity.
Let me know if you need some help.

**Pull request closed without merging**
